set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

set nocompatible

set nu
set cursorline
set cul          "cursorline的缩写形式"

set showmatch

set tabstop=4
set shiftwidth=4
set autoindent
set paste
set listchars=tab:>-,trail:-

set laststatus=2
set ruler

set incsearch
set ignorecase
set smartcase

set t_Co=256

set showmode

