" put this file on home dir ~
set encoding=utf-8
set fileformat=unix 
set ff=unix "set endfile syle is unix LF filetype plugin on " 
set ts=4 
set ruler 
set number 
set smarttab 
set shiftwidth=4 
set tabstop=4 
set shiftwidth=4 
set autoindent "Auto indent 
set nowrap 
set showcmd 
set nobackup 
set noswapfile 
set cursorline 
" set cursorcolumn 
set showmatch 
set cindent 
set history=100 
set incsearch 
set nocompatible 